spring:
  application:
    name: app
  data:
    mongodb:
      uri: ${MONGODB_URI}
      reactive-repositories:
        enabled: false
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
server:
  port: 8090
